{
 "title": "Estado Mysql",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Server",
    "query": "ANSESDPDB01,ANSESMYSQL,ANSESTSASSRV,ANSESTSASSRV01,ANSESTSASSRV02,ANSESMARIADB01,ANSESMARIADB02,ANSESPRMARIA01,ANSESPRMARIA02,ANSESPRMARIA03,ANSESPRMARIA04,ANSESPRMARIA05"
   },
   {
    "name": "Base",
    "label": "Base",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Estado Mysql",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "/^$Server$/" },
     "item": { "filter": "MySQL: Status" },
     "itemTag": { "filter": "Application: MySQL" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$Server" },
     "item": { "filter": "Version" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Querys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:300",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "$Server: MySQL: ",
        "-"
       ],
       "text": "replaceAlias($Server: MySQL: , -)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/^$Server$/" },
     "item": { "filter": "/.*uer/" },
     "itemTag": { "filter": "Application: MySQL" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Bytes transferidos",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:32",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "$Server: MySQL: Bytes",
        "-"
       ],
       "text": "replaceAlias($Server: MySQL: Bytes, -)"
      },
      {
       "$$hashKey": "object:37",
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "sent",
        "Enviados"
       ],
       "text": "replaceAlias(sent, Enviados)"
      },
      {
       "$$hashKey": "object:35",
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "received",
        "Recibidos"
       ],
       "text": "replaceAlias(received, Recibidos)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/^$Server$/" },
     "item": { "filter": "/.*Bytes/" },
     "itemTag": { "filter": "Application: MySQL" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tamaño Bases",
   "type": "stat",
   "gridPos": { "h": 24, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:32",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "$Server: MySQL: Size of database",
        ".-"
       ],
       "text": "replaceAlias($Server: MySQL: Size of database, .-)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/^$Server$/" },
     "item": { "filter": "$Base" },
     "itemTag": { "filter": "Application: MySQL" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Mysql Commands por second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 3 },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:273",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "$Server: MySQL: Command ",
        "-"
       ],
       "text": "replaceAlias($Server: MySQL: Command , -)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/^$Server$/" },
     "item": { "filter": "/.*Command /" },
     "itemTag": { "filter": "Application: MySQL" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "InnoDB status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 9, "y": 7 },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:194",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "$Server: MySQL: InnoDB ",
        "-"
       ],
       "text": "replaceAlias($Server: MySQL: InnoDB , -)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/^$Server$/" },
     "item": { "filter": "/.*nnoDB/" },
     "itemTag": { "filter": "Application: MySQL" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cant conexiones",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:227",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "$Server: MySQL: ",
        "-"
       ],
       "text": "replaceAlias($Server: MySQL: , -)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/^$Server$/" },
     "item": { "filter": "/.*onne/" },
     "itemTag": { "filter": "Application: MySQL" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:248",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "$Server: MySQL: ",
        "-"
       ],
       "text": "replaceAlias($Server: MySQL: , -)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/^$Server$/" },
     "item": {
      "filter": "MySQL: Aborted clients per second"
     },
     "itemTag": { "filter": "Application: MySQL" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "/^$Server$/" },
     "item": { "filter": "MySQL: Max used connections" },
     "itemTag": { "filter": "Application: MySQL" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 9, "y": 12 },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:86",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "$Server: MySQL: Threads ",
        "-"
       ],
       "text": "replaceAlias($Server: MySQL: Threads , -)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/^$Server$/" },
     "item": { "filter": "/.*hreads/" },
     "itemTag": { "filter": "Application: MySQL" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Temp Tables",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 9, "y": 17 },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:113",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "$Server: MySQL: ",
        "-"
       ],
       "text": "replaceAlias($Server: MySQL: , -)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/^$Server$/" },
     "item": { "filter": "/.*tmp/" },
     "itemTag": { "filter": "Application: MySQL" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tablas",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 20 },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:433",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "$Server: MySQL: Threads ",
        "-"
       ],
       "text": "replaceAlias($Server: MySQL: Threads , -)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/^$Server$/" },
     "item": { "filter": "/.*Open table/" },
     "itemTag": { "filter": "Application: MySQL" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:454",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "$Server: MySQL: Threads ",
        "-"
       ],
       "text": "replaceAlias($Server: MySQL: Threads , -)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/^$Server$/" },
     "item": { "filter": "MySQL: Open tables" },
     "itemTag": { "filter": "Application: MySQL" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}